// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.28.1
// source: api/optionhub.proto

package optionhub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeType int32

const (
	AttributeType_STRING      AttributeType = 0
	AttributeType_NUMBER      AttributeType = 1
	AttributeType_DATE        AttributeType = 2
	AttributeType_OPTION      AttributeType = 3
	AttributeType_MULTISELECT AttributeType = 4
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0: "STRING",
		1: "NUMBER",
		2: "DATE",
		3: "OPTION",
		4: "MULTISELECT",
	}
	AttributeType_value = map[string]int32{
		"STRING":      0,
		"NUMBER":      1,
		"DATE":        2,
		"OPTION":      3,
		"MULTISELECT": 4,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_optionhub_proto_enumTypes[0].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_api_optionhub_proto_enumTypes[0]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_api_optionhub_proto_rawDescGZIP(), []int{0}
}

type EntityType int32

const (
	EntityType_USER      EntityType = 0
	EntityType_SOCIETY   EntityType = 1
	EntityType_EVENT     EntityType = 2
	EntityType_COMMUNITY EntityType = 3
	EntityType_MATERIAL  EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "USER",
		1: "SOCIETY",
		2: "EVENT",
		3: "COMMUNITY",
		4: "MATERIAL",
	}
	EntityType_value = map[string]int32{
		"USER":      0,
		"SOCIETY":   1,
		"EVENT":     2,
		"COMMUNITY": 3,
		"MATERIAL":  4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_optionhub_proto_enumTypes[1].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_api_optionhub_proto_enumTypes[1]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_api_optionhub_proto_rawDescGZIP(), []int{1}
}

type GetAttributesMetadataIn struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityAttributeIds []int64                `protobuf:"varint,1,rep,packed,name=entity_attribute_ids,json=entityAttributeIds,proto3" json:"entity_attribute_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAttributesMetadataIn) Reset() {
	*x = GetAttributesMetadataIn{}
	mi := &file_api_optionhub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesMetadataIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesMetadataIn) ProtoMessage() {}

func (x *GetAttributesMetadataIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_optionhub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesMetadataIn.ProtoReflect.Descriptor instead.
func (*GetAttributesMetadataIn) Descriptor() ([]byte, []int) {
	return file_api_optionhub_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttributesMetadataIn) GetEntityAttributeIds() []int64 {
	if x != nil {
		return x.EntityAttributeIds
	}
	return nil
}

type AttributeMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttributeId       int64                  `protobuf:"varint,1,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Type              AttributeType          `protobuf:"varint,2,opt,name=type,proto3,enum=AttributeType" json:"type,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AllowedOperators  []byte                 `protobuf:"bytes,5,opt,name=allowed_operators,json=allowedOperators,proto3" json:"allowed_operators,omitempty"`
	EntityAttributeId int64                  `protobuf:"varint,20,opt,name=entity_attribute_id,json=entityAttributeId,proto3" json:"entity_attribute_id,omitempty"`
	EntityType        EntityType             `protobuf:"varint,21,opt,name=entity_type,json=entityType,proto3,enum=EntityType" json:"entity_type,omitempty"`
	Label             string                 `protobuf:"bytes,22,opt,name=label,proto3" json:"label,omitempty"`
	IsRequired        bool                   `protobuf:"varint,23,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	OrderIndex        int64                  `protobuf:"varint,24,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	VisibilityRules   []byte                 `protobuf:"bytes,25,opt,name=visibility_rules,json=visibilityRules,proto3" json:"visibility_rules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeMetadata) Reset() {
	*x = AttributeMetadata{}
	mi := &file_api_optionhub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeMetadata) ProtoMessage() {}

func (x *AttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_optionhub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeMetadata.ProtoReflect.Descriptor instead.
func (*AttributeMetadata) Descriptor() ([]byte, []int) {
	return file_api_optionhub_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeMetadata) GetAttributeId() int64 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

func (x *AttributeMetadata) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_STRING
}

func (x *AttributeMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AttributeMetadata) GetAllowedOperators() []byte {
	if x != nil {
		return x.AllowedOperators
	}
	return nil
}

func (x *AttributeMetadata) GetEntityAttributeId() int64 {
	if x != nil {
		return x.EntityAttributeId
	}
	return 0
}

func (x *AttributeMetadata) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_USER
}

func (x *AttributeMetadata) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AttributeMetadata) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *AttributeMetadata) GetOrderIndex() int64 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *AttributeMetadata) GetVisibilityRules() []byte {
	if x != nil {
		return x.VisibilityRules
	}
	return nil
}

type GetAttributesMetadataOut struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	AttributesMetadata map[int64]*AttributeMetadata `protobuf:"bytes,1,rep,name=attributes_metadata,json=attributesMetadata,proto3" json:"attributes_metadata,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAttributesMetadataOut) Reset() {
	*x = GetAttributesMetadataOut{}
	mi := &file_api_optionhub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesMetadataOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesMetadataOut) ProtoMessage() {}

func (x *GetAttributesMetadataOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_optionhub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesMetadataOut.ProtoReflect.Descriptor instead.
func (*GetAttributesMetadataOut) Descriptor() ([]byte, []int) {
	return file_api_optionhub_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttributesMetadataOut) GetAttributesMetadata() map[int64]*AttributeMetadata {
	if x != nil {
		return x.AttributesMetadata
	}
	return nil
}

var File_api_optionhub_proto protoreflect.FileDescriptor

const file_api_optionhub_proto_rawDesc = "" +
	"\n" +
	"\x13api/optionhub.proto\"K\n" +
	"\x17GetAttributesMetadataIn\x120\n" +
	"\x14entity_attribute_ids\x18\x01 \x03(\x03R\x12entityAttributeIds\"\xb3\x03\n" +
	"\x11AttributeMetadata\x12!\n" +
	"\fattribute_id\x18\x01 \x01(\x03R\vattributeId\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.AttributeTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12+\n" +
	"\x11allowed_operators\x18\x05 \x01(\fR\x10allowedOperators\x12.\n" +
	"\x13entity_attribute_id\x18\x14 \x01(\x03R\x11entityAttributeId\x12,\n" +
	"\ventity_type\x18\x15 \x01(\x0e2\v.EntityTypeR\n" +
	"entityType\x12\x14\n" +
	"\x05label\x18\x16 \x01(\tR\x05label\x12\x1f\n" +
	"\vis_required\x18\x17 \x01(\bR\n" +
	"isRequired\x12\x1f\n" +
	"\vorder_index\x18\x18 \x01(\x03R\n" +
	"orderIndex\x12)\n" +
	"\x10visibility_rules\x18\x19 \x01(\fR\x0fvisibilityRulesB\x0e\n" +
	"\f_description\"\xd9\x01\n" +
	"\x18GetAttributesMetadataOut\x12b\n" +
	"\x13attributes_metadata\x18\x01 \x03(\v21.GetAttributesMetadataOut.AttributesMetadataEntryR\x12attributesMetadata\x1aY\n" +
	"\x17AttributesMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.AttributeMetadataR\x05value:\x028\x01*N\n" +
	"\rAttributeType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x01\x12\b\n" +
	"\x04DATE\x10\x02\x12\n" +
	"\n" +
	"\x06OPTION\x10\x03\x12\x0f\n" +
	"\vMULTISELECT\x10\x04*K\n" +
	"\n" +
	"EntityType\x12\b\n" +
	"\x04USER\x10\x00\x12\v\n" +
	"\aSOCIETY\x10\x01\x12\t\n" +
	"\x05EVENT\x10\x02\x12\r\n" +
	"\tCOMMUNITY\x10\x03\x12\f\n" +
	"\bMATERIAL\x10\x042b\n" +
	"\x10OptionhubService\x12N\n" +
	"\x15GetAttributesMetadata\x12\x18.GetAttributesMetadataIn\x1a\x19.GetAttributesMetadataOut\"\x00B\x0fZ\rpkg/optionhubb\x06proto3"

var (
	file_api_optionhub_proto_rawDescOnce sync.Once
	file_api_optionhub_proto_rawDescData []byte
)

func file_api_optionhub_proto_rawDescGZIP() []byte {
	file_api_optionhub_proto_rawDescOnce.Do(func() {
		file_api_optionhub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_optionhub_proto_rawDesc), len(file_api_optionhub_proto_rawDesc)))
	})
	return file_api_optionhub_proto_rawDescData
}

var file_api_optionhub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_optionhub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_optionhub_proto_goTypes = []any{
	(AttributeType)(0),               // 0: AttributeType
	(EntityType)(0),                  // 1: EntityType
	(*GetAttributesMetadataIn)(nil),  // 2: GetAttributesMetadataIn
	(*AttributeMetadata)(nil),        // 3: AttributeMetadata
	(*GetAttributesMetadataOut)(nil), // 4: GetAttributesMetadataOut
	nil,                              // 5: GetAttributesMetadataOut.AttributesMetadataEntry
}
var file_api_optionhub_proto_depIdxs = []int32{
	0, // 0: AttributeMetadata.type:type_name -> AttributeType
	1, // 1: AttributeMetadata.entity_type:type_name -> EntityType
	5, // 2: GetAttributesMetadataOut.attributes_metadata:type_name -> GetAttributesMetadataOut.AttributesMetadataEntry
	3, // 3: GetAttributesMetadataOut.AttributesMetadataEntry.value:type_name -> AttributeMetadata
	2, // 4: OptionhubService.GetAttributesMetadata:input_type -> GetAttributesMetadataIn
	4, // 5: OptionhubService.GetAttributesMetadata:output_type -> GetAttributesMetadataOut
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_optionhub_proto_init() }
func file_api_optionhub_proto_init() {
	if File_api_optionhub_proto != nil {
		return
	}
	file_api_optionhub_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_optionhub_proto_rawDesc), len(file_api_optionhub_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_optionhub_proto_goTypes,
		DependencyIndexes: file_api_optionhub_proto_depIdxs,
		EnumInfos:         file_api_optionhub_proto_enumTypes,
		MessageInfos:      file_api_optionhub_proto_msgTypes,
	}.Build()
	File_api_optionhub_proto = out.File
	file_api_optionhub_proto_goTypes = nil
	file_api_optionhub_proto_depIdxs = nil
}
