// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: api/optionhub.proto

package optionhub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptionhubService_GetAttributesMetadata_FullMethodName = "/OptionhubService/GetAttributesMetadata"
)

// OptionhubServiceClient is the client API for OptionhubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptionhubServiceClient interface {
	GetAttributesMetadata(ctx context.Context, in *GetAttributesMetadataIn, opts ...grpc.CallOption) (*GetAttributesMetadataOut, error)
}

type optionhubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptionhubServiceClient(cc grpc.ClientConnInterface) OptionhubServiceClient {
	return &optionhubServiceClient{cc}
}

func (c *optionhubServiceClient) GetAttributesMetadata(ctx context.Context, in *GetAttributesMetadataIn, opts ...grpc.CallOption) (*GetAttributesMetadataOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributesMetadataOut)
	err := c.cc.Invoke(ctx, OptionhubService_GetAttributesMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptionhubServiceServer is the server API for OptionhubService service.
// All implementations must embed UnimplementedOptionhubServiceServer
// for forward compatibility.
type OptionhubServiceServer interface {
	GetAttributesMetadata(context.Context, *GetAttributesMetadataIn) (*GetAttributesMetadataOut, error)
	mustEmbedUnimplementedOptionhubServiceServer()
}

// UnimplementedOptionhubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptionhubServiceServer struct{}

func (UnimplementedOptionhubServiceServer) GetAttributesMetadata(context.Context, *GetAttributesMetadataIn) (*GetAttributesMetadataOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributesMetadata not implemented")
}
func (UnimplementedOptionhubServiceServer) mustEmbedUnimplementedOptionhubServiceServer() {}
func (UnimplementedOptionhubServiceServer) testEmbeddedByValue()                          {}

// UnsafeOptionhubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptionhubServiceServer will
// result in compilation errors.
type UnsafeOptionhubServiceServer interface {
	mustEmbedUnimplementedOptionhubServiceServer()
}

func RegisterOptionhubServiceServer(s grpc.ServiceRegistrar, srv OptionhubServiceServer) {
	// If the following call pancis, it indicates UnimplementedOptionhubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptionhubService_ServiceDesc, srv)
}

func _OptionhubService_GetAttributesMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesMetadataIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionhubServiceServer).GetAttributesMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptionhubService_GetAttributesMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionhubServiceServer).GetAttributesMetadata(ctx, req.(*GetAttributesMetadataIn))
	}
	return interceptor(ctx, in, info, handler)
}

// OptionhubService_ServiceDesc is the grpc.ServiceDesc for OptionhubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptionhubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OptionhubService",
	HandlerType: (*OptionhubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttributesMetadata",
			Handler:    _OptionhubService_GetAttributesMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/optionhub.proto",
}
