// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	model "optionhub-service/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDbRepo is a mock of DBRepo interface.
type MockDbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepoMockRecorder
}

// MockDbRepoMockRecorder is the mock recorder for MockDbRepo.
type MockDbRepoMockRecorder struct {
	mock *MockDbRepo
}

// NewMockDbRepo creates a new mock instance.
func NewMockDbRepo(ctrl *gomock.Controller) *MockDbRepo {
	mock := &MockDbRepo{ctrl: ctrl}
	mock.recorder = &MockDbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbRepo) EXPECT() *MockDbRepoMockRecorder {
	return m.recorder
}

// AddOS mocks base method.
func (m *MockDbRepo) AddOS(ctx context.Context, name, uuid string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOS", ctx, name, uuid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOS indicates an expected call of AddOS.
func (mr *MockDbRepoMockRecorder) AddOS(ctx, name, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOS", reflect.TypeOf((*MockDbRepo)(nil).AddOS), ctx, name, uuid)
}

// GetOsByID mocks base method.
func (m *MockDbRepo) GetOsByID(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOsByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOsById indicates an expected call of GetOsById.
func (mr *MockDbRepoMockRecorder) GetOsById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOsByID", reflect.TypeOf((*MockDbRepo)(nil).GetOsByID), ctx, id)
}

// GetOsBySearchName mocks base method.
func (m *MockDbRepo) GetOsBySearchName(ctx context.Context, name string) ([]model.OS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOsBySearchName", ctx, name)
	ret0, _ := ret[0].([]model.OS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOsBySearchName indicates an expected call of GetOsBySearchName.
func (mr *MockDbRepoMockRecorder) GetOsBySearchName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOsBySearchName", reflect.TypeOf((*MockDbRepo)(nil).GetOsBySearchName), ctx, name)
}
