syntax = "proto3";

option go_package = "pkg/optionhub";

//import  "google/protobuf/empty.proto";
//import  "google/protobuf/timestamp.proto";

service OptionhubService {
  rpc GetAttributesMetadata (GetAttributesMetadataIn) returns (GetAttributesMetadataOut){};
}

message GetAttributesMetadataIn {
  repeated int64 entity_attribute_ids = 1;
}

enum AttributeType {
  STRING = 0;
  NUMBER = 1;
  DATE = 2;
  OPTION = 3;
  MULTISELECT = 4;
}

enum EntityType {
  USER = 0;
  SOCIETY = 1;
  EVENT = 2;
  COMMUNITY = 3;
  MATERIAL = 4;
}

message AttributeMetadata {
  int64 attribute_id = 1;
  AttributeType type = 2;
  string name = 3;
  optional string description = 4;
  bytes allowed_operators = 5;

  int64 entity_attribute_id = 20;
  EntityType entity_type = 21;
  string label = 22;
  bool is_required = 23;
  int64 order_index = 24;
  bytes visibility_rules = 25;
}

message GetAttributesMetadataOut {
  map<int64, AttributeMetadata> attributes_metadata = 1;
}